modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="shieldmod" #mandatory
version="1.1" #mandatory
displayName="Murky's Many Shields" #mandatory
logoFile="Logo.png" #optional
credits="Nicholas Reeder" #optional
authors="MurkyConspiracy" #optional
description='''
Murky's Many Shields adds a few shields using vanilla resources and effects!
'''
[[dependencies.shieldmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="BEFORE"
    side="BOTH"
